### ISSUE TITLE
Install via npm

### ISSUE THREAD

**Issue by MathRobin** [JoppeSchwartz/event-calendar#11]
Please make it available via NPM :)

**Comment by JoppeSchwartz** [comment]
I'll take a look. Do you use all Polymer components via npm?

**Comment by MathRobin** [comment]
I try when I'm able too. I prefer the npm style instead of bower's one (non-objective criteria). It's not really complicated to deploy to npm. Just complete package.json and make `npm publish`. Ask help if needed ;)

**Comment by JoppeSchwartz** [comment]
Thanks - I was just curious. It hadn't occurred to me to use npm instead of bower, but it seems simple enough. (Famous last words.)

**Comment by JoppeSchwartz** [comment]
And how would you recommend dependencies upon components not published via npm be handled in the package.json? Using the GitHub URL method?

**Comment by MathRobin** [comment]
Yes, why not ? It's not the easiest thing but could be great. Each time I use a package which is available on bower and not on npm. I ask the owner like here to make it available. I hope a day, we will have both available on all packages ;)

**Comment by JoppeSchwartz** [comment]
And how do you install dependent Polymer components via npm, as they have no package.json file?

**Comment by MathRobin** [comment]
I Just have to deal without it... Not the funkiest approach

**Comment by JoppeSchwartz** [comment]
Closing as npm lacks support for dependent Polymer components.
